### ISSUE TITLE
Flash Alert "Slug has already been taken" When Uploading Gemfile.lock

### ISSUE THREAD

**Issue by nathanberg** [railsbump/app#104]
## Description

When I try to upload my Gemfile.lock file to [railsbump.org](https://www.railsbump.org/lockfiles/new), I receive a flash alert message stating "Slug has already been taken". This issue occurs even when I use a known good Gemfile.lock file from another comment in a different issue. 

## Steps to Reproduce

- Navigate to https://www.railsbump.org/lockfiles/new.
- Upload a Gemfile.lock file. For testing purposes, I used [this Gemfile.lock](https://raw.githubusercontent.com/fastruby/points/refs/heads/main/Gemfile.lock) from the [fastruby/points](https://github.com/fastruby/points) repository.
- Click on the "Check Now" button.

## Expected Behavior

The Gemfile.lock file should be uploaded successfully.
The application should analyze the dependencies without any errors.

## Actual Behavior

A flash alert message appears stating "Slug has already been taken".
The upload fails, and no analysis is performed.

## Screenshot

<img width="733" alt="Screenshot 2024-11-13 at 12 16 24 PM" src="https://github.com/user-attachments/assets/0f5450fd-15a7-4b94-81cd-6bad06a74209">

## Additional Context

I first encountered this issue with my own Gemfile.lock file.
To rule out any file-specific issues, I tried using a known good Gemfile.lock from [this comment](https://github.com/railsbump/app/issues/101#issuecomment-2444468848), but the same error occurred.
This suggests the problem is not specific to any particular Gemfile.lock file.
My browser and OS details:
Browser: Safari - Version 18.1 (20619.2.8.11.10)
Operating System: MacOS Sequoia - 15.1

**Comment by etagwerker** [comment]
@nathanberg Thanks for submitting this issue! I've found it in the past so I think it should be easy to reproduce. 

I see two potential solutions: (1) Redirect to the existing slug or (2) change the way that the slug is calculated. The way it gets generated is based on the gem names: https://github.com/railsbump/app/blob/3ea9a311c1e5a6d0e6bd2cb682c6a61adb2acf4f/app/models/lockfile.rb#L45-L49 

I'm inclined to go with (1) -- Thoughts?

**Comment by nathanberg** [comment]
@etagwerker I agree with your inclination of using option (1).

Really appreciate you looking into this so quickly!

**Comment by etagwerker** [comment]
@nathanberg This should now be patched in production. Thank you! 🙏🏼
