### ISSUE TITLE
Gemfile.lock scan is broken

### ISSUE THREAD

**Issue by Alchiman** [railsbump/app#110]
Hi I just tried using the "Check a lock file" feature and got a 500 when I pasted the .lock content and hit Checknow. let me know how can I help.

**Comment by etagwerker** [comment]
@Alchiman Thanks for submitting this issue! I believe it was related to #108 and it was solved by #109 

I just tested that it is working fine with this Gemfile.lock: https://gist.github.com/etagwerker/73c8d38f8e6712701886338b20a78413 (Gitlab's Gemfile.lock) 

Please try again and let me know if you still run into the 500 error. Thank you! 🙏🏼
