### ISSUE TITLE
Cannot search for a gem or a Gemfile

### ISSUE THREAD

**Issue by aivaco** [railsbump/app#63]
There's something wrong with the project. When I tried to look for a gem or Gemfile.lock, it returned me this error:
![imagen](https://user-images.githubusercontent.com/7002433/120383185-ce546680-c2e1-11eb-8a5c-0cb72fd8e33d.png)

**Comment by aivaco** [comment]
I forgot to thank you for this project. It looks really helpful

**Comment by manuelmeurer** [comment]
It throws a `ActionController::InvalidAuthenticityToken`, weird...
I'll have a look at it!

And thanks for the thank-you, really appreciated! 🙇‍♂️ 🙏

**Comment by manuelmeurer** [comment]
Fixed!

**Comment by manuelmeurer** [comment]
The problem was Cloudflare/Heroku/SSL: https://bloggie.io/@kinopyo/heroku-free-dyno-with-cloudflare-free-ssl
