### ISSUE TITLE
suggestion to move off Heroku and onto render.com

### ISSUE THREAD

**Issue by ckhall** [railsbump/app#70]
https://render.com might be a good alternative to heroku to get away from the 30 second request timeouts.

https://render.com/render-vs-heroku-comparison

**Comment by manuelmeurer** [comment]
I tried Render.com for another app back in March and really liked them, but the deploys were unbearably slow.
https://community.render.com/t/slow-deploys-trying-to-find-out-why/3771
Hatchbox.io is much nicer, I'll move Railsbump there! 😄

**Comment by manuelmeurer** [comment]
I investigated some more and it seems like Fly.io is another great Heroku alternative with a lot of the same ideas.

**Comment by manuelmeurer** [comment]
We're live on Fly.io! 🎉
