### ISSUE TITLE
Production slowdown? 

### ISSUE THREAD

**Issue by etagwerker** [railsbump/app#71]
Hi @manuelmeurer,

It seems that there are a lot of gems in "Checking..." status. Can I be of assistance to sort this out? 

<img width="1175" alt="Screen Shot 2022-10-14 at 2 54 25 PM" src="https://user-images.githubusercontent.com/17584/195920485-04cd9693-c630-4752-9ef7-2b1262da28e3.png">

I guess it might be that the background jobs are not being processed... 🤔 

Please let me know.

Thanks!

**Comment by manuelmeurer** [comment]
Hey @etagwerker,

Thanks for letting me know!
I'm in the process of updating the app to Rails 7, and moving from Heroku to Fly.io, and it seems like I killed the background worker in the process... 🙈
It's not back on and processing all pending gems!
