### ISSUE TITLE
Compatible versions via hovering over the thump-up icon? 

### ISSUE THREAD

**Issue by almokhtarbr** [railsbump/app#72]
Hello, months ago I was able to hover the mouse over the thumbs-up icon and was showing what compatible versions, now it won't work with me tried to change the browsers tried (safari, brave, chrome, Firefox) none of them works ! Am I missing something ? 
Thank you so much for this project, it helps a lot!

**Comment by manuelmeurer** [comment]
Should be fixed, thanks for reporting! 👍
