### ISSUE TITLE
Railsbump down? Cloudflare SSL handshake fails

### ISSUE THREAD

**Issue by dpaola2** [railsbump/app#74]

**Comment by manuelmeurer** [comment]
Thanks for the ping, @dpaola2! Seems to be a problem with Cloudflare...
I'm trying to find out what happened.

**Comment by dpaola2** [comment]
Seems like it's working again! Thanks 😀

**Comment by manuelmeurer** [comment]
Finally! The SSL certs from Cloudflare and Fly.io were battling each other for a while... ⚔️

**Comment by clveranis** [comment]
Unfortunately it looks like the site is down again for the same issue.

**Comment by clveranis** [comment]
Sounds good! I saw it was down, waited a few days, then saw that it was still down so I figured I would make you aware. Hopefully it doesn't take too much to get it back up, its a great app and I thank you for it!

**Comment by manuelmeurer** [comment]
Finally back up and not using Cloudflare SSL anymore, so this issue should (hopefully) not reappear.
