### ISSUE TITLE
would be easier to use if it was a CLI tool instead of web only

### ISSUE THREAD

**Issue by dfuentes77** [railsbump/app#76]
This web tool seems to have some issues or slowness in loading and be a bit cumbersome to use.  A cli tool would be easier.  Are there any that you might recommend that do the same as this?

**Comment by manuelmeurer** [comment]
Sorry, don't know of any.
It would be a good idea for RailsBump to have an API and CLI tool, I agree.
Happy to review a PR if you have time!
