### ISSUE TITLE
Lockfile (Gemfile.lock) for Rails v7 checking is taking too long.

### ISSUE THREAD

**Issue by orbulant** [railsbump/app#79]
<img width="269" alt="Screenshot 2024-01-10 at 3 06 20 PM" src="https://github.com/railsbump/app/assets/36763167/3b6a6177-546f-42c9-a2c9-320167a2d0ce">

The version checking for Rails 7 version is taking forever to load. While the others are working just fine.

<img width="1342" alt="Screenshot 2024-01-10 at 3 07 29 PM" src="https://github.com/railsbump/app/assets/36763167/2e9e5735-1274-4819-8ec2-45e3bf863df4">

**Comment by manuelmeurer** [comment]
Working on it! 😄

**Comment by mattdrewitt** [comment]
@manuelmeurer Any chance there is an update to this situation? I'd love to make use of this to help with a rails 7 upgrade that is having some hard to find errors and knowing if theres an incompatibility would be a big help. Thanks!

**Comment by manuelmeurer** [comment]
Alright, I had to fix a few things, but now we're back in action: https://github.com/railsbump/checker/actions

The problem is that about 78,000 pending checks have accumulated over time... 😱
Each check takes about 10s to finish, so we're looking at 9 days until all are done.
