### ISSUE TITLE
Bug: pg gem shows wrong status

### ISSUE THREAD

**Issue by arielj** [railsbump/app#96]
Since the `pg` gem doesn't have any restriction and any version can be installed in any Rails version, the site reports `all` for most versions:

![image](https://github.com/user-attachments/assets/9d03200b-a5d3-407f-ac20-5fb3c573d267)

https://www.railsbump.org/gems/pg

But Rails 5.0 removed the support of pg < 9.1 https://guides.rubyonrails.org/5_0_release_notes.html#active-record-removals
And Rails 6.0 removed support of pg < 9.3 https://guides.rubyonrails.org/6_0_release_notes.html#active-record-notable-changes

**Comment by etagwerker** [comment]
@arielj Thanks for submitting this! Unless there is a machine-readable way to check for this, it will be very hard to implement. 

Feel free to re-open if you can find a machine-readable format that has this information. 👍🏼
