### ISSUE TITLE
Frontend fails to request some JS files

### ISSUE THREAD

**Issue by arielj** [railsbump/app#97]
![image](https://github.com/user-attachments/assets/a83fa4ba-5320-4f71-ba1d-666b7a8fbc9f)

```
       GET https://www.railsbump.org/qwerty/js/script.js 404 (Not Found)
       GET https://kit.fontawesome.com/0d43dadb44.js net::ERR_ABORTED 403 (Forbidden)
```

How to reproduce:
- just open the home page with dev tools open

**Comment by etagwerker** [comment]
@manuelmeurer I don't see anything broken even with this JS load error. Do you remember why these resources were needed? 

@arielj Do you see any of the icons broken due to the fontawesome load error?

**Comment by arielj** [comment]
yeah, the icons are missing for me, from the HTML I should see a github icon at the top right next to the other nav links, but nothing

![image](https://github.com/user-attachments/assets/3fa62316-dc98-409e-9ed6-19cbe084f700)

I tried with Chrome, Firefox and Opera and it's the same in the three browsers
